spring:
  application:
    name: spring-ai-llama
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: llama3.1
      chat:
        options:
          model: llama3.1 # ou 3.1
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true