spring:
  application:
    name: spring-ai-llama
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
      chat:
        options:
          model: llama3.1
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 768 # necessário alterar também tabela no banco postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    baseline-on-migrate: true
