spring:
  profiles:
    active: local

  application:
    name: backend-spring-ai

  datasource:
    username: postgres
    password: postgres

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    sql-migration-prefix: V
    validate-on-migrate: true
    baseline-version: 0
    repair: true
    locations: classpath:db.migration
    enable: true

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 768

api:
  security:
    token:
      secret: my-secret-key
      expiration-hours: 2

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  ai:
    ollama:
      base-url: http://localhost:11434
  docker:
    compose:
      lifecycle-management: NONE
filePath: e://ArquivosUsuarios
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5433/postgres-docker
  ai:
    ollama:
      base-url: http://ollama-llm:11434
  docker:
    compose:
      lifecycle-management: START_AND_STOP
filePath: /app/data